include:
  - path: hasura/docker-compose.hasura.yaml

services:
  auth-server:
    build:
      context: .
      dockerfile: auth-server/Dockerfile
      args:
        JWT_SECRET: ${JWT_SECRET}
    ports:
      - "8080:8080"
    env_file:
      - ./auth-server/.env
    volumes:
      - ./auth-server:/app
      - /app/tmp
